name: debug

on:
  workflow_dispatch:
    inputs:
      build_with_cache:
        description: 'Enable docker build cache'
        required: false
        default: "true"
        
      push_docker_images:
        description: 'Push built docker images to docker hub'
        required: false
        default: "false"
      
      update_dockerhub_readme:
        description: 'Update the README hosted on the docker hub project site'
        required: false
        default: "false"
        
      synapse_version_name:
        description: 'Name of synapse release version (eg: v1.42.0)'
        required: true
        default: "v1.42.0"
        
      create_github_release_tag:
        description: 'Create a github repository release tag'
        required: false
        default: "false"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: echo "build_with_cache=${{ github.event.inputs.build_with_cache }} push_docker_images=${{ github.event.inputs.push_docker_images }} update_dockerhub_readme=${{ github.event.inputs.update_dockerhub_readme }} synapse_version_name=${{ github.event.inputs.synapse_version_name }} create_github_release_tag=${{ github.event.inputs.create_github_release_tag }}"
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        if: ${{ github.event.inputs.build_with_cache == 'true' }}
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.event.inputs.push_docker_images == 'true' }}
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ github.event.inputs.push_docker_images == 'true' }}
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_REGISTRY_USERNAME }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}

      - name: Build and push docker image with version tag
        uses: docker/build-push-action@v2
        id: docker-build
        with:
          platforms: linux/amd64,linux/arm64
          build-args: TAG=${{ github.event.inputs.synapse_version_name }}
          push: ${{ github.event.inputs.push_docker_images == 'true' }}
          tags: |
            dotwee/matrix-synapse-s3:latest
            dotwee/matrix-synapse-s3:${{ github.event.inputs.synapse_version_name }}
            ghcr.io/dotwee/matrix-synapse-s3:latest
            ghcr.io/dotwee/matrix-synapse-s3:${{ github.event.inputs.synapse_version_name }}

      - name: Update Docker Hub repository description
        uses: peter-evans/dockerhub-description@v2
        if: ${{ github.event.inputs.update_dockerhub_readme == 'true' }}
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          repository: dotwee/matrix-synapse-s3

      - name: Create a GitHub repository release tag
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.event.inputs.create_github_release_tag == 'true' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: ${{ github.event.inputs.synapse_version_name }}
          prerelease: ${{ contains(github.event.inputs.synapse_version_name, 'rc') }}
          automatic_release_tag: ${{ github.event.inputs.synapse_version_name }}
