name: Dependabot Auto-Merge

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - ready_for_review

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Dependabot PRs
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"