name: build and publish docker image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
      
  release:
    types: [published]
      
  create:
  page_build:
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up qemu
        uses: docker/setup-qemu-action@v1

      - name: set up buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          
      - name: login to docker hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
                
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          cache-from: type=registry,ref=${{ steps.prep.outputs.tags }}
          cache-to: type=inline
          build-args: TAG=${{ github.ref }}
          tags: |
            docker.io/dotwee/matrix-synapse-s3:${{ github.sha }}
            docker.io/dotwee/matrix-synapse-s3:${{ github.ref }}
