name: release-cron

on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  validate:
    runs-on: ubuntu-latest

    outputs:
      new: ${{ steps.check.outputs.new }}
      version: ${{ steps.check.outputs.version }}

    steps:
      - name: Install depepndencies
        run: sudo apt-get install -y curl jq
      - name: Check new version
        id: check
        run: |
          synapse_version=`curl -SsL https://api.github.com/repos/matrix-org/synapse/releases | jq -r '.[].tag_name' | head -n 1`
          echo "::set-output name=version::${synapse_version}"
          
          docker_version=`curl -sSL 'https://registry.hub.docker.com/v2/repositories/dotwee/matrix-synapse-s3/tags' | jq -r '."results"[]["name"] | select(.=="'${synapse_version}'")'`
          if [ "${synapse_version}" == "${docker_version}" ]; then
            echo "::set-output name=new::false"
          else
            echo "::set-output name=new::true"
          fi
      - name: Print outputs
        run: echo version=${{steps.check.outputs.version}}  new=${{steps.check.outputs.new}}

  release:
    runs-on: ubuntu-latest
    needs: validate
    if: needs.validate.outputs.new == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_REGISTRY_USERNAME }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          build-args: TAG=${{ needs.validate.outputs.version }}
          push: true
          tags: |
            dotwee/matrix-synapse-s3:${{ needs.validate.outputs.version }}
            ghcr.io/dotwee/matrix-synapse-s3:${{ needs.validate.outputs.version }}

      - name: Push latest
        if: ${{ !contains( needs.validate.outputs.version , 'rc') }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          build-args: TAG=${{ needs.validate.outputs.version }}
          push: true
          tags: |
            dotwee/matrix-synapse-s3:latest
            ghcr.io/dotwee/matrix-synapse-s3:latest

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          repository: dotwee/matrix-synapse-s3
