name: build and publish docker image releases

on:
  release:
    types: 
      - published
      - created
  
  page_build:
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up qemu
        uses: docker/setup-qemu-action@v1

      - name: set up buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          
      - name: login to docker hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          
      - name: login to github container registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_REGISTRY_USERNAME }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
      
      - name: get tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
                
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: TAG=${{ steps.tag_name.outputs.SOURCE_TAG }}
          tags: |
            dotwee/matrix-synapse-s3:${{ steps.tag_name.outputs.SOURCE_TAG }}
            dotwee/matrix-synapse-s3:latest
            ghcr.io/dotwee/matrix-synapse-s3:${{ steps.tag_name.outputs.SOURCE_TAG }}
            ghcr.io/dotwee/matrix-synapse-s3:latest
